services:
  api:
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
      - sqlite_data:/app/prisma
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
    command: sh -c "npm run db:seed && npm run dev"
volumes:
  sqlite_data: